print("      /-----------------\ \n")
print("     /                   \ \n")
print("     |   --         --   | \n")
print("     |         |         | \n")
print("     |         0         | \n")
print("     |    \_________/    | \n")
print("     |                   | \n")
print("     |         |         | \n")
print("      \-----------------/ \n")